name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  args: --severity-threshold=high

    docker:
        needs: security
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and test development image
              run: |
                  docker build -t calculator-dev -f Dockerfile.dev .
                  docker run --rm -v "$(pwd):/app" -w /app calculator-dev sh -c "npm install && npm run format && npm run lint && npm test"

    browser:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Install Playwright browsers
              run: |
                  docker build -t calculator-dev -f Dockerfile.dev .
                  docker run --rm -v "$(pwd):/app" -w /app calculator-dev sh -c "npm install && npx playwright install --with-deps"

            - name: Run Playwright tests
              run: |
                  docker run --rm -v "$(pwd):/app" -w /app calculator-dev sh -c "npm run test:browser"
